AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/awardload.rake'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

